/**
 * Rover operating state as reported by telemetry.
 */
export type RoverState = "IDLE" | "DRIVING" | "CHARGING" | "FAULT" | "ESTOP";

/**
 * A single telemetry reading broadcast over Socket.IO and stored in the DB.
 */
export interface TelemetryPayload {
  id?: string;
  batteryVoltage: number;
  temperature: number;
  state: RoverState;
  timestamp: string;
}

/**
 * Body accepted by the manual "trigger mock telemetry" endpoint/event.
 * All fields are optional — anything omitted is generated by the server.
 * The server validates and clamps every field; it never trusts these
 * values blindly.
 */
export interface TriggerTelemetryInput {
  batteryVoltage?: number;
  temperature?: number;
  state?: RoverState;
}

export const ROVER_STATES: readonly RoverState[] = [
  "IDLE",
  "DRIVING",
  "CHARGING",
  "FAULT",
  "ESTOP",
];

/** Reasonable physical bounds used for validation on the backend. */
export const TELEMETRY_BOUNDS = {
  batteryVoltage: { min: 0, max: 60 },
  temperature: { min: -40, max: 120 },
} as const;
